### ISSUE TITLE
UploadCare not working on Netlify CMS (Loading...)

### ISSUE THREAD

**Issue by ositaka** [thriveweb/yellowcake#28]
Hello,

I've just tested a fresh copy of the yellowcake, created an API Key on UploadCare (to set as "publicKey" on the` /static/admin/config.yml`) and I've logged into netlify-cms and tried to add a file on the "media", but it's not working... Just shows the message "**Loading...**" and doesn't resolve.

Can anyone help, and see if something has changed, please?  
I've the impression it was working, like, 2 weeks ago.

I am new to Gatsby and I didn't know about this tool,
it seems to be a must have on a modern website :)

Thank you for the help!

**Comment by SpacemanPete** [comment]
I ran into the same problem this week when scaffolding a new site. 
I did a bit of digging and it looks like there is some additional config needed to enable the UploadCare service when using the npm dependency `netlify-cms-app` instead of `netlify-cms`, mentioned here: https://github.com/netlify/netlify-cms/issues/2950#issuecomment-562510021

I tried the recommendation there, but I'm still getting an error from `npm run start`:
```
✖ 4 problems (0 errors, 4 warnings)

success Building development bundle - 13.559s
 ERROR  Failed to compile with 11 errors                                                                                                                    1:15:32 PM
⠀
These dependencies were not found:
⠀
* codemirror in ./node_modules/netlify-cms-widget-code/dist/esm/CodeControl.js, ./node_modules/react-codemirror2/index.js
* codemirror/keymap/emacs in ./node_modules/netlify-cms-widget-code/dist/esm/CodeControl.js
* codemirror/keymap/sublime in ./node_modules/netlify-cms-widget-code/dist/esm/CodeControl.js
* codemirror/keymap/vim in ./node_modules/netlify-cms-widget-code/dist/esm/CodeControl.js
* codemirror/lib/codemirror.css in ./node_modules/netlify-cms-widget-code/dist/esm/CodeControl.js
* codemirror/mode in ./node_modules/netlify-cms-widget-code/dist/esm/CodeControl.js
* codemirror/theme/material.css in ./node_modules/netlify-cms-widget-code/dist/esm/CodeControl.js
* netlify-cms-backend-proxy in ./node_modules/netlify-cms-app/dist/esm/extensions.js
* netlify-cms-lib-util/src in ./node_modules/netlify-cms-backend-gitlab/dist/esm/implementation.js
* netlify-cms-media-library-uploadcare in ./src/cms/media-libraries.js
⠀
To install them, you can run: npm install --save codemirror codemirror/keymap/emacs codemirror/keymap/sublime codemirror/keymap/vim codemirror/lib/codemirror.css code
mirror/mode codemirror/theme/material.css netlify-cms-backend-proxy netlify-cms-lib-util/src netlify-cms-media-library-uploadcare
```

Seems like the root bug is with `netlify-cms-app` rather than this Yellowcake starter repo and then package.json here will need to be updated to fix. If I have time I plan to tackle this over the weekend. But if anyone else knows what to do here then I'm all ears.

**Comment by ositaka** [comment]
Hello @SpacemanPete, thanks for the answer, I see what can be the problem then. 

Today I've started using another starter, the "gatsbro" — as I could get the "media"working. I am making a simple website for a family member and I am very fresh on Gatsby, but I really wanna go for it!

Thanks for your reply!

**Comment by LeibGarber** [comment]
same. also unable to make new posts

**Comment by SpacemanPete** [comment]
@ositaka @LeibGarber, I submitted a PR to hopefully resolve the issue in this starter repo: https://github.com/thriveweb/yellowcake/pull/29

I just deployed the PR updates to my Netlify test site and UploadCare was working for me.
Until I hear back on review/approval of my PR, perhaps you can test it out for yourselves and let me know if it works for you as well.

**Note**: I wasn't able to validate it in a local Dev environment when I switched `static/admin/config.yml` `branch: name:` to `test-repo`, but it did work fine when I published it to Netlify.

**Comment by ositaka** [comment]
Hello @SpacemanPete, thanks for the answer. I've tried to make a codesandbox from the PR and it is still not working. I get a message on the console referring to a  

`cms.js:sourcemap:1 Uncaught TypeError: Cannot read property 'replace' of undefined
    at t.default.listFiles (cms.js:sourcemap:1)
    at t.default.getMedia (cms.js:sourcemap:1)
    at t.default.getMedia (cms.js:sourcemap:1)
    at R.getMedia (cms.js:sourcemap:1)
    at cms.js:sourcemap:1`

Here is the link for the sandbox: https://codesandbox.io/s/yellowcake-uploadcare-fix-9dlom 
The netlify url is this one: https://csb-qmv41.netlify.com/ and you can register on the /admin/ to try it out.

**Comment by SpacemanPete** [comment]
hi @ositaka,
I'm not sure about testing in the codesandbox, since you need to have Netlify Identity and Git Gateway enabled to login and publish changes from the backend. I was able to register and login to your Netlify site and I see the Media box is still showing "Loading..." 

Before deploying it to Netlify, did you create your own API KEY on UploadCare and add your site domain to the UploadCare domain whitelist in the settings panel?

**Comment by ositaka** [comment]
I am trying to fix this with this run `npm i --s netlify-cms-media-library-uploadcare` and registering this dependency on /src/cms/cms.js 

I think it will work now, I will reply in a few minutes.

**Comment by SpacemanPete** [comment]
My PR makes those two changes already so I assume that somehow your latest Netlify build didn't include them in the deployment. If you test the build by merging my PR with your deployment branch (`master`, `staging`, etc ) locally then pushing your changes to trigger a deployment, then it should work

**Comment by ositaka** [comment]
@SpacemanPete Now it is working, but I believe something is not at 100%. 
The "media" page it disappears from the home at /admin/ but I am able to upload an image with the UI of UploadCare.

**Comment by SpacemanPete** [comment]
Yeah, I discovered that the other day as well, I assume it's a limitation of the Uploadcare API similar to the issue [netlify-cms#2966](https://github.com/netlify/netlify-cms/issues/2966), since there's no logic to pull details of the images already uploaded.

To be honest, given these issues I'm not convinced the UploadCare integration is robust enough for real-world usage yet. The inability to reuse images already uploaded is a bit of a deal-breaker for me at the moment.

I'm planning on refactoring [my fork of Yellowcake starter](https://github.com/SpacemanPete/yellowcake) this weekend to use Netlify Large Media since it seems like it would be a more robust integration of media files right in the same git repo and is has transformation service up to 25k a month on the free tier, which should be plenty fine for most small projects. Keep an eye on my repo if you're interested.

**Comment by ositaka** [comment]
@SpacemanPete I will be watching that repo! I really thought this UploadCare would be a nice solution, with the ability to "connect" to 3rd-party storage, like G-Drive, Dropbox and even the photos of the smartphone... It is a shame then :( 

Thanks for your time and patient! all the best*

**Comment by baldeagle** [comment]
I would also like to mention that upload care recently increased their middle tier from $20ish to $45ish.
I'm looking forward to changing integrations as well.

**Comment by ositaka** [comment]
@baldeagle and @SpacemanPete I think you guys can solve this issue just by switching from the UploadCare to Cloudinary (it's free).

I am making a website for a photographer and I've just realized I couldn't really send the raw photo-files of +10mb to GitHub, so, I had in mind it was there another media library cloud system - Cloudinary! I've just added this on my `config.yml` file: 

```
media_library:
  name: cloudinary
  config:
    cloud_name: username
    api_key: to_replace_with_api_key
```

You can find more info here: 
https://www.netlifycms.org/docs/cloudinary/


PS: I've added this Cloudinary on the website and it works like a charm, very professional and you are sure the photos are uploaded and not lost in the Space!

**Comment by Firthir** [comment]
I'll look into this. Great info here.

**Comment by Firthir** [comment]
Thanks @SpacemanPete
